sudo: required

env:
 - CABALVER=1.22 GHCVER=7.10.3

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER hlint
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

before_script:
  - cabal --version
  - cabal update
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - ghc-pkg list
  - cabal sandbox init

script:
  - cabal install --enable-tests --enable-benchmarks --enable-documentation --only-dependencies
  - cabal configure -v2 --enable-tests --enable-benchmarks --enable-coverage
  - cabal build
  - cabal test
  - cabal install --enable-tests --enable-benchmarks --enable-documentation 
  - cabal sdist
  - ghc-pkg list
  - hlint src --cpp-define HLINT

after_script:
  - cabal install hpc-coveralls
  - .cabal-sandbox/bin/hpc-coveralls --exclude-dir=test lexerTest 
  - cabal install codecov-haskell
  - .cabal-sandbox/bin/codecov-haskell --exclude-dir=test lexerTest
