language: haskell
ghc: 7.10.2
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - cabal install codecov-haskell
  - codecov-haskell --exclude-dir=test lexerTest 
