matrix:
  include:
   - env: CABALVER=1.18 GHCVER=7.8.4
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.18
          - ghc-7.8.4
   
sudo: false

# The packages from the PPA don't put this into the PATH automatically.
install:
  - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
  - cabal --version
  - cabal update
  - ghc --version
  - ghc-pkg list
  - cabal sandbox init

script:
  - cabal install --enable-tests --enable-benchmarks --enable-documentation --only-dependencies
  - cabal configure --enable-tests --enable-benchmarks --enable-coverage
  - cabal build
  - cabal test
  - cabal install --enable-tests --enable-benchmarks --enable-documentation 
  - cabal sdist

after_script:
  - ghc-pkg list
  - cabal install codecov-haskell
  - .cabal-sandbox/bin/codecov-haskell --exclude-dir=test --display-report lexerTest 
