matrix:
  include:
   - env: CABALVER=1.22 GHCVER=7.10.3
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.22
          - ghc-7.10.3
   
sudo: false

# The packages from the PPA don't put this into the PATH automatically.
install:
 - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
  - cabal --version
  - cabal update
  - ghc --version
  - ghc-pkg list
  - cabal install codecov-haskell

script:
  - cabal install --enable-tests --enable-documentation --enable-coverage --only-dependencies
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - run-cabal-test
  - cabal install --enable-documentation 
  - cabal sdist

after_script:
  - ghc-pkg list
  - codecov-haskell --exclude-dir=test lexerTest 
